### ISSUE TITLE
Hi there!  I made some edits in a fork, would you care to collab?

### ISSUE THREAD

**Issue by CptSpaceToaster** [trinchan/slackbot#3]
Hello, I made some significant changes to the slackbot, over in my [fork](https://github.com/trinchan/slackbot/compare/master...CptSpaceToaster:master)

You probably won't agree with everything I've done, but I'd like to start a conversation, and maybe figure out if there's anything I've done that you want, or if you want to collaborate further in any way!

In order, the [commits/summaries](https://github.com/CptSpaceToaster/slackbot/commits/master) are
- [x] Cleaned up some scheme errors/warnings when the server recieves an outgoing webhook/command  
- [x] Quick hack to enable one slackbot to service multiple slack servers
- [x] Changed Outgoing webhook parseing to simply assume the first character is junk, and the command follows it immediatly.  (e.g. `!ping`)
- [x] Significant modifications to the README.md (Hopefully to improve clarity and setup instructions)

Are you interested in some of this work?  If not, that's cool.  I'll happily maintain my own fork, I simply wanted to extend a hand, instead of just outright stealing the entire project...

Checkbox what you want (if anything) and I'll PR

**Comment by trinchan** [comment]
Hey @CptSpaceToaster ! Thanks for the contributions, look great. Glad to see someone is making use of this project :+1: . Over the next few days, I'll open issues for some ideas I've had. I'd love for more collaboration.

**Comment by CptSpaceToaster** [comment]
Alrighty, the modifications to the README will take a bit, but I think I can get most of this later this evening.

**Comment by CptSpaceToaster** [comment]
Bump: https://github.com/trinchan/slackbot/pull/4

**Comment by CptSpaceToaster** [comment]
Bomp: https://github.com/trinchan/slackbot/pull/4
