### ISSUE TITLE
No robots registered after uploading to Heroku

### ISSUE THREAD

**Issue by iozz** [trinchan/slackbot#6]
I've started learning GO not so long ago, and I try to use this project to develop Slack robots in GO :)

However I don't manage to get this working on Heroku, the robots don't register themselves... It works great when launched locally, either by hand or with `foreman start`...
On Heroku I don't see the `Registered: ...` traces, and get the `No robot for that command yet :(` answer.

Before deploying I do `go generate ./...` and `go install ./...`.

Is there anything I do wrong?

**Comment by trinchan** [comment]
@iozz are you using the go heroku build pack from heroku? if so, it is not set up to run `go generate ./...` before installing so the bot registry file will not be generated. i made a [fork of the build pack](https://github.com/trinchan/heroku-buildpack-go) myself that runs `go generate ./...` before installing, but it may be out of date from latest go build pack. Regardless, I use it for my slackbot instance.

**Comment by iozz** [comment]
Hi, thanks a lot, using your fork, it works for the slash commands. I need to investigate a bit for the outgoing webhook but as I said, I'm a noob :)
I thought that running go `generate ./...` locally was enough, and missed the fact that the server has to run it also during deployment.

**Comment by johnboiles** [comment]
Just adding another data point: I'm also new to go and this wasn't very clear to me from the readme!

**Comment by johnboiles** [comment]
Forgive me if this is a n00b question, but why have `importer/init.go` in `.gitignore` at all? Seems like removing that would enable slackbot to work out of the box with the standard Heroku buildpack?
